#pragma once
#include <array>
#include <string_view>
#include <optional>
#include <cstddef>
#include <cassert>
#include <string>

namespace soa {

	namespace itemid
	{
		enum ItemId : uint16_t {
			Cutlass = 0,
			Pirate_Cutlass,
			Sky_Cutlass,
			Admiral_Cutlass,
			Assassin_Blade,
			Thunder_Cutlass,
			Iron_cutter,
			Nasr_Cutlass,
			Sword_of_Daccat,
			Hunters_Sword,
			Stonecutter,
			Dream_Cutlass,
			Windslicer,
			Vorlik_Blade,
			Suiran_Blade,
			Soul_Sword,
			Boomerang,
			Skywing,
			Scout_Wing,
			Ice_Splitter,
			Leather_Crescent,
			Throwing_Blade,
			Hunting_Arc,
			Valuarang,
			Yin_Wing,
			Dancing_Arc,
			Wing_of_Hope,
			Storm_Wing,
			Moon_Wing,
			Hydra_Wing,
			Grendel_Wing,
			Flutter_Blade,
			Cupil,
			Cupil_Lance,
			Cupil_Star,
			Cupicone,
			Cupil_Spear,
			Cupil_Blade,
			Cupil_Sword,
			Cupil_Cutlass,
			Cupil_Claymore,
			Cupil_Cannon,
			Cupil_Spike,
			Cupil_Weight,
			Cupil_Pan,
			Cupil_Club,
			Cupil_Hammer,
			Final_Cupil,
			Artificial_Arm,
			Hook_Hand,
			Mace_Hand,
			Mining_Arm,
			Dragon_Arm,
			Beak_Hand,
			De_Loco_Drill,
			Excavation_Arm,
			Ruin_Arm,
			Silver_Arm,
			Rapier,
			Stoneblade,
			Imperial_Blade,
			Serpent_Strike,
			Frostblade,
			Blade_of_Slumber,
			Gilders_Own,
			Nasr_Pistol,
			Warriors_Pistol,
			Valuan_Pistol,
			Marksman_Gun,
			Daccat_Custom,
			Gilder_Special,
			Tuna_Cutlass,
			Swirlmerang,
			Sky_Fang,

			Vyses_Uniform = 80,
			Aikas_Shorts,
			Finas_Robe,
			Drachmas_Shirt,
			Enriques_Coat,
			Gilders_Mail,
			Light_Robe,
			Valuan_Uniform,
			Sailor_Uniform,
			Mystic_Dress,
			Valuan_Armor,
			Elastamor,
			Raincoat,
			Nasrean_Mail,
			Ceramic_Armor,
			Agile_Robe,
			Miners_Overalls,
			Fiber_Robe,
			Golden_Armor,
			Ixatakan_Armor,
			Naval_Uniform,
			Nasr_Uniform,
			Caravan_Armor,
			Holy_Robe,
			Daccats_Tunic,
			Battleworn_Armor,
			Miracle_Robe,
			Scale_Mail,
			Soranchu_Robe,
			Long_Robe,
			Captains_Cloak,
			Blessed_Robe,
			Insulated_Mail,
			Vengeance_Armor,
			Swift_Dress,
			Gaia_Cape,
			Robe_of_Faith,
			Plated_Armor,
			Robe_of_Truth,
			Berzerker_Mail,
			Light_Dress,
			Focus_Robe,
			Nasr_Combat_Mail,
			De_Loco_Armor,
			Maidens_Armor,
			Heavy_Armor,
			Ancient_Robe,
			De_Loco_Mail,
			Daccats_Armor,
			Moss_Armor,
			Moonlight_Robe,
			Silver_Armor,
			Victory_Mail,
			Flame_Mantle,
			Female_Armor,
			Ghost_Mail,
			Light_Coat,
			Fiber_Mail,
			Moon_Robe,

			Gemstone_Ring = 160,
			Prophets_Sand,
			Meditation_Ring,
			Moondust_Ring,
			Lovers_Ring,
			Jade_Swirl_Ring,
			Cupil_Ring,
			Warriors_Heart,
			Throkryns_Scale,
			Thryllaks_Scale,
			Maroccas_Shell,
			Buroccas_Shell,
			Crylhounds_Claw,
			Hunters_Hand,
			Thiefs_Aura,
			Quetya_Feather,
			Vigoros_Chain,
			Sailors_Buckler,
			Warriors_Rune,
			Ancient_Bracer,
			Counter_Bracer,
			Defensive_Aura,
			Ivy_Band,
			Silvite_Ring,
			Gem_of_Fluidity,
			Wind_Gem_Ring,
			Eye_of_Truth,
			Revered_Voice,
			Everlasting_Gem,
			Behemoths_Ring,
			Constitution_Gem,
			Nomadic_Veil,
			Radiant_Fur,
			Sand_Storm_Ring,
			Skull_Cap,
			Mages_Bane,
			Blue_Rogue_Patch,
			Assassin_Ring,
			Stealth_Ring,
			Dhabu_Hide,
			Ominous_Mask,
			Flash_Ribbon,
			The_Unseen_Hand,
			Crescent_Amulet,
			Skyseer_Goggles,
			Nocturnal_Sight,
			Critical_Vision,
			Gem_of_Purity,
			Shard_of_Purity,
			Fortune_Ring,
			Black_Map,
			White_Map,
			Captains_Hat,
			Mesh_Tights,
			Black_Eyepatch,
			Silver_Veil,
			Imperial_Crest,
			Gilders_Amulet,
			Valuan_Medallion,
			Immunity_Ring,
			Thermo_Ring,
			Slayer_Ring,
			Chance_Ring,

			Sacri_Crystal = 240,
			Sacres_Crystal,
			Sacrum_Crystal,
			Sacrulen_Crystal,
			Magic_Droplet,
			Magic_Dew,
			Aura_of_Valor,
			Soul_Crystal,
			Unholy_Dagger,
			Curia_Crystal,
			Risan_Crystal,
			Riselem_Crystal,
			Glyph_of_Might,
			Glyph_of_Speed,
			Healing_Salve,
			Chalice_of_Blood,
			Windsong_Orb,
			Winter_Orb,
			Moonberry,
			Cham,
			Paranta_Seed,
			Icyl_Seed,
			Zaal_Seed,
			Dexus_Seed,
			Sylph_Seed,
			Vidal_Seed,
			Magus_Seed,
			Pyri_Box,
			Pyrum_Box,
			Crystales_Box,
			Crystalen_Box,
			Wevles_Box,
			Wevlen_Box,
			Electri_Box,
			Electrum_Box,
			Sacri_Box,
			Sacrum_Box,
			Riselem_Box,
			Sylenis_Box,
			Panika_Box,
			Driln_Box,
			Slipara_Box,
			Eternum_Box,
			Rune_of_Ill_Omen,
			Golden_Mask,
			Sky_Sardis,
			Red_Sardis,
			Flying_Fish,
			Spiked_Sunfish,
			Abirik_Cham,
			Chom,
			Gold_Pollen,
			Ilchymix,
			Orb_of_Serenity,
			Kabal_Skewer,
			Moms_Skewer,
			Tropica,
			Uralas_Lunch,
			Polly_Special,
			Magillex_Idol,
			Pharax_Idol,
			Euconyx_Idol,

			Drajik_Fish = 305,
			Kite_Ray,
			Stealth_Ray,
			Spear_Squid,
			Drill_Squid,
			Grule,
			Rainbow_Grule,
			Sky_Jellyfish,
			Silverfish,
			Romuhai_Fish,
			Hamahai_Fish,
			Nerath_Eel,
			Great_Nerath_Eel,
			Red_Dragon,
			Gold_Dragon,

			Green_Crystal = 320,
			Red_Crystal,
			Purple_Crystal,
			Blue_Crystal,
			Yellow_Crystal,

			Green_Moon_Stone = 326,
			Red_Moon_Stone,
			Purple_MoonStone,
			Blue_Moon_Stone,
			Yellow_MoonStone,
			Silver_MoonStone,
			Underwater_Suit,
			Note_in_a_Bottle,
			Cannon_Room_Key,
			Ship_Schematics,
			Gonzales_Map,
			Pedros_Map,

			Golden_Mans_Eye = 339,
			Great_Birds_Eye,
			Raw_Moon_Stone,
			Daccats_Coin,

			Kabal = 344,
			Gentum,
			Khale,

			Valuan_Passport = 348,
			Moon_Stone_Fuel,
			Claras_Purse,
			Book_of_Polarity,
			Velorium,

			Harbor_Key = 355,
			Magic_Cannon,
			Wages,
			Grapor_Meat,
			Domingos_Title,
			Moonfish,
			Black_Spot_1,
			Black_Spot_2,
			Black_Spot_3,
			Black_Spot_4,

			Main_Cannon = 400,
			Standard_Cannon,
			Heavy_Cannon,
			G_Type_Cannon,
			B_Type_Cannon,
			Prototype_Cannon,
			Advanced_Cannon,
			Yamato_Spirit,
			Ancient_Cannon,
			X_Cannon,
			_3_Inch_Cannon,
			_3_Inch_Blaster,
			_5_Inch_Cannon,
			_8_Inch_Cannon,
			_12_Inch_Cannon,
			_10_Inch_Cannon,
			_10_Inch_Cannon_Coil,
			_12_Inch_Blaster,
			_3_Foot_Cannon,
			_5_Foot_Cannon,
			Light_Torpedo,
			Guided_Torpedo,
			Shock_Torpedo,
			Hunter_Torpedo,
			Valuan_Torpedo,
			Heavy_Torpedo,
			Serpent_Torpedo,
			Flash_Torpedo,
			Arcwhale_Torpedo,
			Dragon_Torpedo,
			Harpoon_Cannon,
			MoonStone_Cannon,
			Moon_Cannon,
			Moon_Gun,
			Moon_Torpedo,
			Pyril_Cannon,
			Wevl_Cannon,
			Electril_Torpedo,
			Crystil_Cannon,
			Kazai_Gun,

			Rogue_Figure = 440,
			Pryn_Figure,
			Pyrynn_Figure,
			Arcwhale_Figure,
			Quetya_Figure,
			Giant_Figure,
			Bluheim_Figure,
			Goddess_Figure,
			Vyse_Figure,
			Spherical_Figure,
			Engine_Cover,
			Turbo_Kit,
			Bore_up_Kit,
			Twin_Propellers,
			Air_Intake,
			Twin_Turbo,
			Timing_Valve,
			Triple_Turbo,
			High_Torque_Kit,
			Double_Shaft,
			Armored_Deck,
			Steel_Deck,
			Slanted_Deck,
			Compound_Deck,
			Heavy_Armor_Deck,
			Alloy_Deck,
			Dragon_Deck,
			Ancient_Deck,
			Silver_Deck,
			Sparkling_Deck,
			Intercom,
			Enhanced_Kitchen,
			Floor_Heater,
			Air_Purifier,
			Yafutoman_Alcove,
			Soundproofing,
			Expensive_Wheel,
			Chandelier,
			Wooden_Doll,
			Indoor_Plant,

			Bomb = 480,
			Big_Bomb,
			Concussion_Bomb,
			Shredder_Bomb,
			Pyro_Bomb,
			Frost_Bomb,
			Silencer_Bomb,
			Thunder_Bomb,
			Electro_Bomb,
			Wave_Bomb,
			Repair_Kit,
			Deluxe_Kit,
			Magic_Kit,
			Complete_Kit,
			Gear_Grease,
			Thermal_Grease,
			Captains_Stripe,
			Apa_Wax,
			Apo_Wax,
			Speed_Wax,
			Hybrid_Wax,
			Heat_Sensor,
			Rudder_Grease,
			Machine_Oil,
			Light_Alloy,
			Hex_Shell,
			Magic_Shell,
			Gold_Bullion,
			Crystal_Ball,
			Magic_Cannon_item,
		};
	}

	namespace text {

		inline constexpr auto PCNames = std::to_array<std::string_view>({
			"Vyse",
			"Aika",
			"Fina",
			"Drachma",
			"Enrique",
			"Gilder"
			});

		inline constexpr auto EnemyNames = std::to_array<std::string_view>({
			"Soldier",
			"Guard",
			"Seeker",
			"Marocca",
			"Grouder",
			"Spell Warden",
			"Flestik",
			"Basallish",
			"Mind Stealer",
			"Walrenk",
			"Varkris",
			"Azbeth",
			"Zivilyn Bane",
			"Ghastling",
			"Florast",
			"Tsirat",
			"Thorkryn",
			"Scorfly",
			"Centralk",
			"Feralisk",
			"Ferlith",
			"Crylhound",
			"Magma Tiki",
			"Salamander",
			"Baroo",
			"Dung Fly",
			"Death's Head",
			"Looper",
			"Loopalon",
			"Tsurak",
			"Enforcer",
			"Serpantis",
			"Dralnog",
			"Que'lak",
			"Pinalisk",
			"Crylbeast",
			"Slothstra",
			"Polraxis",
			"Roseln",
			"Elooper",
			"Grapor",
			"Sphyrus",
			"Iridzu",
			"Flyst",
			"Medulizk",
			"Lucich",
			"Digger",
			"Flat Fiend",
			"Burocca",
			"Drogerp",
			"Nadnarb",
			"Nairad",
			"Kanezl",
			"Mantoid",
			"Sorcerer",
			"Slithar",
			"Golooper",
			"Alusphere",
			"Soldier",
			"Delzool",
			"Defender",
			"Ghrost",
			"Graver",
			"Shrilp",
			"Cerosik",
			"Carnilak",
			"Valgand",
			"Berserker",
			"Lurgel Tank",
			"Tenkou",
			"Patrol Guard",
			"Mine Patrol",
			"Frost Worm",
			"Destroyer",
			"Marauder",
			"Guardian",
			"Telsor",
			"Dorntak",
			"Linark",
			"Dolthstra",
			"Dracolurg",
			"Garagor",
			"Kilite",
			"Imezl",
			"Lurker",
			"Jellikra",
			"Scorpon",
			"Arclooper",
			"Tsorok",
			"Sentry",
			"Langry",
			"Durel Beetle",
			"Totelm",
			"Thryllak",
			"Stonebeak",
			"Razorbeak",
			"Stalk Fiend",
			"Kantor",
			"Shadow",
			"Assassin",
			"Officer",
			"Mage Warden",
			"Shock Troop",
			"Red Guard",
			"Elite Guard",
			"Jynnus",
			"Hydra Elite",
			"Yulooper",
			"Hunter",
			"Zivilyn Bane",
			"Zivilyn Bane",
			"Zivilyn Bane",
			"Zivilyn Bane",
			"Zivilyn Bane",
			"Zivilyn Bane",
			"Zivilyn Bane",
			"Hunter",
			"Delvax",
			"Hopril",
			"Elcian",
			"Antonio",
			"Sentinel",
			"Bleigock",
			"Executioner"
			"Galcian",
			"Royal Guard",
			"Rokwyrm"
			"Antonio 2",
			"Rik'talish",
			"Sinistra",
			"Destra",
			"Ramirez",
			"Vigoro",
			"Dralkor Tank",
			"Tortigar",
			"Jao",
			"Mao",
			"Muraji",
			"Veltarn",
			"Vigoro",
			"Dracoslyth",
			"Galcian",
			"Ramirez",
			"Ramirez",
			"Eliminator",
			"Gordo",
			"Mad Chef",
			"Ramirez",
			"Piastol",
			"Piastol",
			"Piastol",
			"Piastol",
			"Piastol",
			"Piastol",
			"Piastol",
			"Piastol",
			"Piastol",
			"Piastol",
			"Piastol",
			"Piastol",
			"Piastol",
			"Piastol",
			"Piastol",
			"Piastol",
			"Piastol",
			"Piastol",
			"Piastol",
			"Piastol",
			"Tara",
			"Tara",
			"Tara",
			"Tara",
			"Tara",
			"Lira",
			"Lira",
			"Lira",
			"Lira",
			"Lira",
			"Pera",
			"Pera",
			"Pera",
			"Pera",
			"Pera",
			"Daikokuya",
			"Daikokuya",
			"Daikokuya",
			"Daikokuya",
			"Daikokuya",
			"Rupee",
			"Rupee",
			"Rupee",
			"Rupee",
			"Rupee",
			"Rupee",
			"Rupee",
			"Rupee",
			"Rupee",
			"Rupee",
			"Barta",
			"Barta",
			"Barta",
			"Barta",
			"Barta",
			"Vize",
			"Vize",
			"Vize",
			"Vize",
			"Vize",
			"Anita",
			"Anita",
			"Anita",
			"Anita",
			"Anita",
			"Faina",
			"Faina",
			"Faina",
			"Faina",
			"Faina",
			"Lord Bane",
			"Lord Bane",
			"Lord Bane",
			"Lord Bane",
			"Lord Bane",
			"Gunarm",
			"Gunarm",
			"Gunarm",
			"Gunarm",
			"Gunarm",
			"Vigoro",
			"Vigoro",
			"Vigoro",
			"Vigoro",
			"Vigoro",
			"DeathHound",
			"DeathHound",
			"DeathHound",
			"DeathHound",
			"Youjin",
			"Youjin",
			"Boo",
			"Boo",
			"Zivilyn Bane",
			"Zivilyn Bane",
			"Frock",
			"Frock"
		});

		constexpr std::string_view get_enemy_name(std::size_t id) {
			// Optional bounds check (keep or drop for speed).
			assert(id < EnemyNames.size());
			return EnemyNames[id];
		}

		inline constexpr auto ItemNames = std::to_array<std::string_view>({ //TODO: Fix this list so that it aligns with item_id
			"Cutlass",
			"Pirate Cutlass",
			"Sky Cutlass",
			"Admiral Cutlass",
			"Assassin Blade",
			"Thunder Cutlass",
			"Iron-cutter",
			"Nasr Cutlass",
			"Sword of Daccat",
			"Hunter's Sword",
			"Stonecutter",
			"Dream Cutlass",
			"Windslicer",
			"Vorlik Blade",
			"Suiran Blade",
			"Soul Sword",
			"Boomerang",
			"Skywing",
			"Scout Wing",
			"Ice Splitter",
			"Leather Crescent",
			"Throwing Blade",
			"Hunting Arc",
			"Valuarang",
			"Yin Wing",
			"Dancing Arc",
			"Wing of Hope",
			"Storm Wing",
			"Moon Wing",
			"Hydra Wing",
			"Grendel Wing",
			"Flutter Blade",
			"Cupil",
			"Cupil Lance",
			"Cupil Star",
			"Cupicone",
			"Cupil Spear",
			"Cupil Blade",
			"Cupil Sword",
			"Cupil Cutlass",
			"Cupil Claymore",
			"Cupil Cannon",
			"Cupil Spike",
			"Cupil Weight",
			"Cupil Pan",
			"Cupil Club",
			"Cupil Hammer",
			"Final Cupil",
			"Artificial Arm",
			"Hook Hand",
			"Mace Hand",
			"Mining Arm",
			"Dragon Arm",
			"Beak Hand",
			"De Loco Drill",
			"Excavation Arm",
			"Ruin Arm",
			"Silver Arm",
			"Rapier",
			"Stoneblade",
			"Imperial Blade",
			"Serpent Strike",
			"Frostblade",
			"Blade of Slumber",
			"Gilder's Own",
			"Nasr Pistol",
			"Warrior's Pistol",
			"Valuan Pistol",
			"Marksman Gun",
			"Daccat Custom",
			"Gilder Special",
			"Tuna Cutlass",
			"Swirlmerang",
			"Sky Fang",
			"",
			"",
			"",
			"",
			"",
			"",
			"Vyse's Uniform",
			"Aika's Shorts",
			"Fina's Robe",
			"Drachma's Shirt",
			"Enrique's Coat",
			"Gilder's Mail",
			"Light Robe",
			"Valuan Uniform",
			"Sailor Uniform",
			"Mystic Dress",
			"Valuan Armor",
			"Elastamor",
			"Raincoat",
			"Nasrean Mail",
			"Ceramic Armor",
			"Agile Robe",
			"Miner's Overalls",
			"Fiber Robe",
			"Golden Armor",
			"Ixa'takan Armor",
			"Naval Uniform",
			"Nasr Uniform",
			"Caravan Armor",
			"Holy Robe",
			"Daccat's Tunic",
			"Battleworn Armor",
			"Miracle Robe",
			"Scale Mail",
			"Soranchu Robe",
			"Long Robe",
			"Captain's Cloak",
			"Blessed Robe",
			"Insulated Mail",
			"Vengeance Armor",
			"Swift Dress",
			"Gaia Cape",
			"Robe of Faith",
			"Plated Armor",
			"Robe of Truth",
			"Berzerker Mail",
			"Light Dress",
			"Focus Robe",
			"Nasr Combat Mail",
			"De Loco Armor",
			"Maiden's Armor",
			"Heavy Armor",
			"Ancient Robe",
			"De Loco Mail",
			"Daccat's Armor",
			"Moss Armor",
			"Moonlight Robe",
			"Silver Armor",
			"Victory Mail",
			"Flame Mantle",
			"Female Armor",
			"Ghost Mail",
			"Light Coat",
			"Fiber Mail",
			"Moon Robe",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"Gemstone Ring",
			"Prophet's Sand",
			"Meditation Ring",
			"Moondust Ring",
			"Lover's Ring",
			"Jade Swirl Ring",
			"Cupil Ring",
			"Warrior's Heart",
			"Throkryn's Scale",
			"Thryllak's Scale",
			"Marocca's Shell",
			"Burocca's Shell",
			"Crylhound's Claw",
			"Hunter's Hand",
			"Thief's Aura",
			"Quetya Feather",
			"Vigoro's Chain",
			"Sailor's Buckler",
			"Warrior's Rune",
			"Ancient Bracer",
			"Counter Bracer",
			"Defensive Aura",
			"Ivy Band",
			"Silvite Ring",
			"Gem of Fluidity",
			"Wind Gem Ring",
			"Eye of Truth",
			"Revered Voice",
			"Everlasting Gem",
			"Behemoth's Ring",
			"Constitution Gem",
			"Nomadic Veil",
			"Radiant Fur",
			"Sand Storm Ring",
			"Skull Cap",
			"Mage's Bane",
			"Blue Rogue Patch",
			"Assassin Ring",
			"Stealth Ring",
			"Dhabu Hide",
			"Ominous Mask",
			"Flash Ribbon",
			"The Unseen Hand",
			"Crescent Amulet",
			"Skyseer Goggles",
			"Nocturnal Sight",
			"Critical Vision",
			"Gem of Purity",
			"Shard of Purity",
			"Fortune Ring",
			"Black Map",
			"White Map",
			"Captain's Hat",
			"Mesh Tights",
			"Black Eyepatch",
			"Silver Veil",
			"Imperial Crest",
			"Gilder's Amulet",
			"Valuan Medallion",
			"Immunity Ring",
			"Thermo Ring",
			"Slayer Ring",
			"Chance Ring",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"Sacri Crystal",
			"Sacres Crystal",
			"Sacrum Crystal",
			"Sacrulen Crystal",
			"Magic Droplet",
			"Magic Dew",
			"Aura of Valor",
			"Soul Crystal",
			"Unholy Dagger",
			"Curia Crystal",
			"Risan Crystal",
			"Riselem Crystal",
			"Glyph of Might",
			"Glyph of Speed",
			"Healing Salve",
			"Chalice of Blood",
			"Windsong Orb",
			"Winter Orb",
			"Moonberry",
			"Cham",
			"Paranta Seed",
			"Icyl Seed",
			"Zaal Seed",
			"Dexus Seed",
			"Sylph Seed",
			"Vidal Seed",
			"Magus Seed",
			"Pyri Box",
			"Pyrum Box",
			"Crystales Box",
			"Crystalen Box",
			"Wevles Box",
			"Wevlen Box",
			"Electri Box",
			"Electrum Box",
			"Sacri Box",
			"Sacrum Box",
			"Riselem Box",
			"Sylenis Box",
			"Panika Box",
			"Driln Box",
			"Slipara Box",
			"Eternum Box",
			"Rune of Ill Omen",
			"Golden Mask",
			"Sky Sardis",
			"Red Sardis",
			"Flying Fish",
			"Spiked Sunfish",
			"Abirik Cham",
			"Chom",
			"Gold Pollen",
			"Ilchymix",
			"Orb of Serenity",
			"Kabal Skewer",
			"Mom's Skewer",
			"Tropica",
			"Urala's Lunch",
			"Polly Special",
			"Magillex Idol",
			"Pharax Idol",
			"Euconyx Idol",
			"",
			"",
			"",
			"Drajik Fish",
			"Kite Ray",
			"Stealth Ray",
			"Spear Squid",
			"Drill Squid",
			"Grule",
			"Rainbow Grule",
			"Sky Jellyfish",
			"Silverfish",
			"Romuhai Fish",
			"Hamahai Fish",
			"Nerath Eel",
			"Great Nerath Eel",
			"Red Dragon",
			"Gold Dragon",
			"Green Crystal",
			"Red Crystal",
			"Purple Crystal",
			"Blue Crystal",
			"Yellow Crystal",
			"",
			"Green Moon Stone",
			"Red Moon Stone",
			"Purple MoonStone",
			"Blue Moon Stone",
			"Yellow MoonStone",
			"Silver MoonStone",
			"Underwater Suit",
			"Note in a Bottle",
			"Cannon Room Key",
			"Ship Schematics",
			"Gonzales' Map",
			"Pedro's Map",
			"",
			"Golden Man's Eye",
			"Great Bird's Eye",
			"Raw Moon Stone",
			"Daccat's Coin",
			"",
			"Kabal",
			"Gentum",
			"Khale",
			"",
			"Valuan Passport",
			"Moon Stone Fuel",
			"Clara's Purse",
			"Book of Polarity",
			"Velorium",
			"",
			"",
			"Harbor Key",
			"Magic Cannon",
			"Wages",
			"Grapor Meat",
			"Domingo's Title",
			"Moonfish",
			"Black Spot",
			"Black Spot",
			"Black Spot",
			"Black Spot",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"Main Cannon",
			"Standard Cannon",
			"Heavy Cannon",
			"G-Type Cannon",
			"B-Type Cannon",
			"Prototype Cannon",
			"Advanced Cannon",
			"Yamato Spirit",
			"Ancient Cannon",
			"X Cannon",
			"3\"Cannon",
			"3\"Blaster",
			"5\"Cannon",
			"8\"Cannon",
			"12\"Cannon",
			"10\"Cannon",
			"10\"Cannon Coil",
			"12\"Blaster",
			"3'Cannon",
			"5'Cannon",
			"Light Torpedo",
			"Guided Torpedo",
			"Shock Torpedo",
			"Hunter Torpedo",
			"Valuan Torpedo",
			"Heavy Torpedo",
			"Serpent Torpedo",
			"Flash Torpedo",
			"Arcwhale Torpedo",
			"Dragon Torpedo",
			"Harpoon Cannon",
			"MoonStone Cannon",
			"Moon Cannon",
			"Moon Gun",
			"Moon Torpedo",
			"Pyril Cannon",
			"Wevl Cannon",
			"Electril Torpedo",
			"Crystil Cannon",
			"Kazai Gun",
			"Rogue Figure",
			"Pryn Figure",
			"Pyrynn Figure",
			"Arcwhale Figure",
			"Quetya Figure",
			"Giant Figure",
			"Bluheim Figure",
			"Goddess Figure",
			"Vyse Figure",
			"Spherical Figure",
			"Engine Cover",
			"Turbo Kit",
			"Bore-up Kit",
			"Twin Propellers",
			"Air Intake",
			"Twin Turbo",
			"Timing Valve",
			"Triple Turbo",
			"High Torque Kit",
			"Double Shaft",
			"Armored Deck",
			"Steel Deck",
			"Slanted Deck",
			"Compound Deck",
			"Heavy Armor Deck",
			"Alloy Deck",
			"Dragon Deck",
			"Ancient Deck",
			"Silver Deck",
			"Sparkling Deck",
			"Intercom",
			"Enhanced Kitchen",
			"Floor Heater",
			"Air Purifier",
			"Yafutoman Alcove",
			"Soundproofing",
			"Expensive Wheel",
			"Chandelier",
			"Wooden Doll",
			"Indoor Plant",
			"Bomb",
			"Big Bomb",
			"Concussion Bomb",
			"Shredder Bomb",
			"Pyro Bomb",
			"Frost Bomb",
			"Silencer Bomb",
			"Thunder Bomb",
			"Electro Bomb",
			"Wave Bomb",
			"Repair Kit",
			"Deluxe Kit",
			"Magic Kit",
			"Complete Kit",
			"Gear Grease",
			"Thermal Grease",
			"Captain's Stripe",
			"Apa Wax",
			"Apo Wax",
			"Speed Wax",
			"Hybrid Wax",
			"Heat Sensor",
			"Rudder Grease",
			"Machine Oil",
			"Light Alloy",
			"Hex Shell",
			"Magic Shell",
			"Gold Bullion",
			"Crystal Ball",
			"Magic Cannon",
		});
		//static_assert(sizeof(ItemNames) == 510, "size");

		constexpr std::optional<std::size_t> find_item_index(std::string_view name) {
			for (std::size_t i = 0; i < ItemNames.size(); ++i)
				if (ItemNames[i] == name) return i;
			return std::nullopt;
		}

		constexpr std::string_view get_item_name(std::size_t id) {
			// Optional bounds check (keep or drop for speed).
			assert(id < ItemNames.size());
			return ItemNames[id];
		}

		inline constexpr auto ElementNames = std::to_array<std::string_view>({
			"Green",
			"Red",
			"Blue",
			"Yellow",
			"Purple",
			"Silver"
		});		
		
		constexpr std::string_view get_element_name(std::size_t id) {
			// Optional bounds check (keep or drop for speed).
			assert(id >= 0 && id < ElementNames.size());
			return ElementNames[id];
		}
	}

	namespace battle {

		enum TurnType : uint32_t {
			BackAttack = 0,
			Normal = 1,
			Advantage = 2
		};

		constexpr std::string get_turn_type_string(TurnType type) {
			switch (type) {
			case BackAttack: return { "Back Attack" }; case Normal: return { "Normal" }; case Advantage: return { "Advantage" };
		} 
			return "Unknown type";
		}

		enum Elements : uint8_t {
			Green,
			Red,
			Blue,
			Yellow,
			Purple,
			Silver,
		};


	} 
}